<a href="https://colab.research.google.com/github/hitarth2004/numpy-100/blob/master/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#All matrix operations

In [ ]:
import numpy as np

# Define two matrices
A = np.array([[12,15,18], [13,24,15],[16,21,19]])
B = np.array([[15,13,20], [18, 15,21],[11,13,23]])

print("Addition of matrix :\n",np.add(A,B))

print("\n\nSubstraction of matrix :\n",np.subtract(A,B))

print("\n\nMulatiplication of matrix :\n",np.multiply(A,B))

print("\n\Division of matrix :\n",np.divide(A,B))

print("\n\nMod of matrix :\n",np.mod(A,B))

print("\n\nTranspose of matrix :\n",np.transpose(A))

print("\n\nDot product of matrix :\n",np.dot(A,B))

Addition of matrix :
 [[27 28 38]
 [31 39 36]
 [27 34 42]]


Substraction of matrix :
 [[-3  2 -2]
 [-5  9 -6]
 [ 5  8 -4]]


Mulatiplication of matrix :
 [[180 195 360]
 [234 360 315]
 [176 273 437]]

\Division of matrix :
 [[0.8        1.15384615 0.9       ]
 [0.72222222 1.6        0.71428571]
 [1.45454545 1.61538462 0.82608696]]


Mod of matrix :
 [[12  2 18]
 [13  9 15]
 [ 5  8 19]]


Transpose of matrix :
 [[12 13 16]
 [15 24 21]
 [18 15 19]]


Dot product of matrix :
 [[ 648  615  969]
 [ 792  724 1109]
 [ 827  770 1198]]


# Horizontal and vertical stacking of Numpy Arrays

In [ ]:
import numpy as np

# Horizontal stacking
print("Horizontal stacking:")
print(np.hstack((A, B)))

# Vertical stacking
print("\n\nVertical stacking:")
print(np.vstack((A,B)))


Horizontal stacking:
[[12 15 18 15 13 20]
 [13 24 15 18 15 21]
 [16 21 19 11 13 23]]


Vertical stacking:
[[12 15 18]
 [13 24 15]
 [16 21 19]
 [15 13 20]
 [18 15 21]
 [11 13 23]]


# Custom sequence generation


In [ ]:
import numpy as np

# Generate a sequence from 0 to 9 (exclusive)
A = np.arange(10)

# Generate 5 equally spaced values from 0 to 1
B = np.linspace(0, 1, 5)

# Generate 10 logarithmically spaced values from 1 to 100
C = np.logspace(0, 2, 10)

# Print the results
print("arange:")
print(A)

print("\n\nlinspace:")
print(B)

print("\n\nlogspace:")
print(C)


arange:
[0 1 2 3 4 5 6 7 8 9]


linspace:
[0.   0.25 0.5  0.75 1.  ]


logspace:
[  1.           1.66810054   2.7825594    4.64158883   7.74263683
  12.91549665  21.5443469   35.93813664  59.94842503 100.        ]


# Arithmetic and Statistical Operations, Mathematical Operations, Bitwise Operators


In [ ]:
import numpy as np

# Arithmetic operations
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])

# Addition
C = A + B

# Subtraction
D = A - B

# Statistical operations
E = np.mean(A)  # Mean
F = np.max(B)  # Maximum value

# Mathematical operations
G = np.sqrt(A)  # Square root

# Bitwise operators
H = np.bitwise_and(A, B)  # Bitwise AND

# Print the results
print("Addition:")
print(C)

print("\n\nSubtraction:")
print(D)

print("\n\nMean:")
print(E)

print("\n\nMaximum value:")
print(F)

print("\n\nSquare root:")
print(G)

print("\n\nBitwise AND:")
print(H)


Addition:
[ 6  8 10 12]


Subtraction:
[-4 -4 -4 -4]


Mean:
2.5


Maximum value:
8


Square root:
[1.         1.41421356 1.73205081 2.        ]


Bitwise AND:
[1 2 3 0]


# Copying and viewing arrays

In [ ]:
import numpy as np

# Create an array
A = np.array([1, 2, 3, 4, 5])

# Copy the array
B = np.copy(A)
# Alternatively: B = A.copy()

# Create a view of the array
C = A[1:4]
# Alternatively: C = A.view()

# Print the results
print("Copied array:")
print(B)

print("\n\nView of the array:")
print(C)


Copied array:
[1 2 3 4 5]


View of the array:
[2 3 4]


# Data Stacking, Searching, Sorting, Counting, Broadcasting


In [ ]:
import numpy as np
array3= np.loadtxt("stud2.csv",delimiter=",",dtype=str,skiprows=1)
print(array3)

math = []
reading = []
writing = []
group = []
gender = []
level = []
course = []
total = []

for i in array3:
  gender.append(i[0])
  group.append(i[1])
  level.append(i[2])
  course.append(i[3])
  math.append(int(i[4]))
  reading.append(int(i[5]))
  writing.append(int(i[5]))
  total.append([int(i[4]),int(i[5]),int(i[6])])
gender_array = np.array(gender)
group_array = np.array(group)
level_array = np.array(level)
course_array= np.array(course)
math_array = np.array(math)
reading_array = np.array(reading)
writing_array = np.array(writing)
total_array = np.array(total)

[['female' 'group B' "bachelor's degree" 'none' '72' '72' '74']
 ['female' 'group C' 'some college' 'completed' '69' '90' '88']
 ['female' 'group B' "master's degree" 'none' '90' '95' '93']
 ['male' 'group A' "associate's degree" 'none' '47' '57' '44']
 ['male' 'group C' 'some college' 'none' '76' '78' '75']
 ['female' 'group B' "associate's degree" 'none' '71' '83' '78']
 ['female' 'group B' 'some college' 'completed' '88' '95' '92']
 ['male' 'group B' 'some college' 'none' '40' '43' '39']
 ['male' 'group D' 'high school' 'completed' '64' '64' '67']
 ['female' 'group B' 'high school' 'none' '38' '60' '50']
 ['male' 'group C' "associate's degree" 'none' '58' '54' '52']
 ['male' 'group D' "associate's degree" 'none' '40' '52' '43']
 ['female' 'group B' 'high school' 'none' '65' '81' '73']
 ['male' 'group A' 'some college' 'completed' '78' '72' '70']
 ['female' 'group A' "master's degree" 'none' '50' '53' '58']
 ['female' 'group C' 'some high school' 'none' '69' '75' '78']
 ['male' 'grou



---

**1) Average score of female candadtes in maths**






In [ ]:
#Using Searching Method we can find index
x = np.array(np.where(gender_array == 'female'))
#using Average Method
y= np.average(math_array[x])
#using Sum/Len  method
z = np.sum(math_array[x])/(x.size)

print("Average score of feamale candidates is :\n",y,"(Using Average Method)\n",z,"(Using Sum/len methode)" )

Average score of feamale candidates is :
 62.92307692307692 (Using Average Method)
 62.92307692307692 (Using Sum/len methode)




---

**Difference Between Highest Score in reading from Male and Female Candidate**



In [ ]:
#searching
x = np.array(np.where(gender_array == 'male' ))

y = np.array(np.where(gender_array == 'female'))
# by using max function finding max and getting difference
z= np.max(reading_array[y])-np.max(reading_array[x])

print("Difference Between Highest Score in reading from Male and Female Candidate is :",z)

Difference Between Highest Score in reading from Male and Female Candidate is : 6




---

**Total marks of all students**

In [ ]:
# by addition of arrays

z = math_array + reading_array + writing_array

print("Total marks of students are",z)

Total marks of students are [216 249 280 161 232 237 278 126 192 158 166 144 227 222 156 219 266  82
 130 170 204 215 152 215 216 221]




---
**What is lowest and Highest average of all subject**


In [ ]:
# by using we creat array of average

x = np.array([np.average(math_array),np.average(reading_array),np.average(writing_array)])

print("Lowest average is",np.min(x),"of","\nHighest average=",np.max(x))

Lowest average is 62.0 of 
Highest average= 67.73076923076923




---
**What is median marks of every subject**


In [ ]:
x = np.median(math_array)
y = np.median(reading_array)
z = np.median(writing_array)
print("Median marks of math:",x,"\nMedian marks of reading:",y,"\nMedian marks of writing:",z)

Median marks of math: 65.5 
Median marks of reading: 71.5 
Median marks of writing: 71.5
